from __future__ import annotations

from typing import Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from backend.content.pipeline import ContentPipeline
from backend.content.job_store import job_store
from backend.content.video_job import VideoJob, JobStatus
from backend.llm import OllamaClient
from backend.utils import logger

router = APIRouter(prefix="/content", tags=["content-pipeline"])

# Lazily initialised; real app wires this up at startup
_pipeline: Optional[ContentPipeline] = None


def get_pipeline() -> ContentPipeline:
    global _pipeline
    if _pipeline is None:
        _pipeline = ContentPipeline(OllamaClient())
    return _pipeline


# ── Health ─────────────────────────────────────────────────────────────────────

@router.get("/health")
async def content_health() -> dict[str, str]:
    return {"status": "ok"}


# ── Dashboard ──────────────────────────────────────────────────────────────────

@router.get("/status")
async def pipeline_status() -> dict:
    """Return counts of jobs at every status."""
    return get_pipeline().get_status_summary()


@router.get("/jobs")
async def list_jobs(status: Optional[str] = None) -> list[dict]:
    """List all jobs, optionally filtered by status."""
    jobs = job_store.list_all()
    if status:
        try:
            s = JobStatus(status)
            jobs = [j for j in jobs if j.status == s]
        except ValueError:
            raise HTTPException(400, f"Unknown status: {status}")
    return [j.model_dump() for j in jobs]


@router.get("/jobs/{job_id}")
async def get_job(job_id: str) -> dict:
    job = job_store.load(job_id)
    if not job:
        raise HTTPException(404, f"Job {job_id} not found")
    return job.model_dump()


# ── Idea approval gate (Jack Craig Step 1 greenlight) ─────────────────────────

@router.get("/ideas")
async def list_pending_ideas() -> list[dict]:
    """
    Return all ideas awaiting human greenlight.
    Each has: topic, hook, idea_pitch, trend_data, niche.
    """
    ideas = get_pipeline().get_pending_ideas()
    return [
        {
            "job_id": j.job_id,
            "topic": j.topic,
            "hook": j.hook,
            "niche": j.niche,
            "pillar": j.content_pillar,
            "pitch": j.idea_pitch,
            "conflict": j.trend_data.get("conflict", ""),
            "why_now": j.trend_data.get("why_now", ""),
            "created_at": j.created_at.isoformat(),
        }
        for j in ideas
    ]


class ApproveRequest(BaseModel):
    reason: Optional[str] = None  # optional note — not used for approval


class RejectRequest(BaseModel):
    reason: str = ""


@router.patch("/ideas/{job_id}/approve")
async def approve_idea(job_id: str, body: ApproveRequest = ApproveRequest()) -> dict:
    """
    Greenlight an idea → IDEA_APPROVED.
    ScriptWriterAgent will pick it up on the next pipeline run
    and produce a full conflict-arc script + 8 prompt frames.
    """
    try:
        job = get_pipeline().approve_idea(job_id)
    except (KeyError, ValueError) as e:
        raise HTTPException(400, str(e))
    logger.info(f"[Route] Idea {job_id} approved → ScriptWriterAgent queued")
    return {"job_id": job_id, "status": job.status, "message": "Idea approved — script will be generated on next run."}


@router.patch("/ideas/{job_id}/reject")
async def reject_idea(job_id: str, body: RejectRequest = RejectRequest()) -> dict:
    """Reject an idea. Moves to FAILED."""
    try:
        job = get_pipeline().reject_idea(job_id, body.reason)
    except (KeyError, ValueError) as e:
        raise HTTPException(400, str(e))
    return {"job_id": job_id, "status": job.status}


# ── Script + frames review ─────────────────────────────────────────────────────

@router.get("/jobs/{job_id}/frames")
async def get_prompt_frames(job_id: str) -> dict:
    """
    Return the 8 visual prompt frames generated by ScriptWriterAgent.
    Review these before the video generation step.
    Frames are ordered: Hook, Rising Action, Conflict, Comeback 1,
    Second Rising, Second Conflict, Final Comeback, Payoff.
    """
    job = job_store.load(job_id)
    if not job:
        raise HTTPException(404, f"Job {job_id} not found")
    arc_labels = [
        "Hook", "Rising Action", "Conflict", "Comeback 1",
        "Second Rising", "Second Conflict", "Final Comeback", "Payoff",
    ]
    frames_with_labels = [
        {"beat": arc_labels[i] if i < len(arc_labels) else f"Frame {i+1}", "prompt": p}
        for i, p in enumerate(job.prompt_frames)
    ]
    return {
        "job_id": job_id,
        "topic": job.topic,
        "script": job.script,
        "frames": frames_with_labels,
    }


# ── Pipeline triggers ──────────────────────────────────────────────────────────

@router.post("/run/research")
async def run_research() -> dict:
    """
    Run TrendResearcher: generates 5 idea pitches at IDEA_PENDING.
    Call GET /content/ideas afterwards to review and approve.
    """
    jobs = await get_pipeline().run_research()
    return {"ideas_generated": len(jobs), "ids": [j.job_id for j in jobs]}


@router.post("/run/full")
async def run_full_pipeline() -> dict:
    """
    Run the full pipeline pass (processes all IDEA_APPROVED and downstream jobs).
    Stops at IDEA_PENDING — human approval required first.
    """
    results = await get_pipeline().run_full()
    return results


@router.post("/run/agent/{name}")
async def run_agent(name: str) -> dict:
    """Run a single named agent."""
    try:
        jobs = await get_pipeline().run_agent(name)
        return {"agent": name, "processed": len(jobs)}
    except ValueError as e:
        raise HTTPException(404, str(e))


# ── QA approval ───────────────────────────────────────────────────────────────

@router.patch("/jobs/{job_id}/approve")
async def approve_job(job_id: str) -> dict:
    """Approve a QA-passed job → APPROVED (ready for scheduling)."""
    try:
        job = get_pipeline().approve_job(job_id)
    except (KeyError, ValueError) as e:
        raise HTTPException(400, str(e))
    return {"job_id": job_id, "status": job.status}


@router.patch("/jobs/{job_id}/reject")
async def reject_job(job_id: str, body: RejectRequest = RejectRequest()) -> dict:
    try:
        job = get_pipeline().reject_job(job_id, body.reason)
    except (KeyError, ValueError) as e:
        raise HTTPException(400, str(e))
    return {"job_id": job_id, "status": job.status}


# ── Upload timing ──────────────────────────────────────────────────────────────

@router.get("/upload-window")
async def check_upload_window() -> dict:
    """
    Check whether the upload timing window is open using Jack Craig's rules:
    - Last video views/hr < VIEW_VELOCITY_THRESHOLD for VIEW_VELOCITY_WINDOW_HOURS
    - At least UPLOAD_INTERVAL_HOURS since last post
    Returns the next recommended upload time.
    """
    from backend.content.publisher_agent import PublisherAgent
    from backend.llm import OllamaClient
    pub = PublisherAgent(OllamaClient())
    import os
    velocity_threshold = int(os.getenv("VIEW_VELOCITY_THRESHOLD", "100"))
    velocity_window = int(os.getenv("VIEW_VELOCITY_WINDOW_HOURS", "12"))
    interval_hours = int(os.getenv("UPLOAD_INTERVAL_HOURS", "48"))

    velocity_clear = pub._check_velocity_window(velocity_threshold, velocity_window)
    last_post = pub._get_last_post_time()
    scheduled = pub._calculate_post_time()

    return {
        "upload_window_open": velocity_clear,
        "last_post_time": last_post.isoformat() if last_post else None,
        "next_recommended_upload": scheduled.isoformat(),
        "rules": {
            "min_interval_hours": interval_hours,
            "velocity_threshold_views_per_hr": velocity_threshold,
            "velocity_window_hours": velocity_window,
        },
    }

